const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const Hospital = require("./models/hospital");
const Client = require("./models/user");
require("dotenv").config();

const hospitals = [
  {
    name: "City Hospital",
    email: "admin@cityhospital.com",
    id: "CITY001",
    password: "City@123", // Original: City@123
    phone: "9876543210",
    address: "123 Mumbai Street",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400001",
    specDrName: "A. Sharma",
    numberOfDoctors: 45,
    numberOfNurses: 80,
    aboutHospital:
      "Leading multi-specialty hospital in Mumbai with state-of-the-art facilities and experienced medical professionals.",
    website: "https://cityhospital.com",
    openingHours: { start: "09:00", end: "18:00" },
    experience: "15",
    specialist: "Cardiologist",
    languagesSpoken: "English, Hindi, Marathi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MD",
    emergencyContact: "9876543211",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Sunshine Hospital",
    email: "contact@sunshinehospital.com",
    id: "SUN001",
    password: "Sunshine@123", // Original: Sunshine@123
    phone: "9876543220",
    address: "456 Delhi Avenue",
    city: "Delhi",
    state: "Delhi",
    zipCode: "110001",
    specDrName: "B. Singh",
    numberOfDoctors: 50,
    numberOfNurses: 90,
    aboutHospital:
      "Premier healthcare facility in Delhi providing comprehensive medical services with modern infrastructure.",
    website: "https://sunshinehospital.com",
    openingHours: { start: "10:00", end: "20:00" },
    experience: "10",
    specialist: "Orthopedic",
    languagesSpoken: "English, Hindi, Punjabi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MS",
    emergencyContact: "9876543221",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Apollo Hospital",
    email: "info@apollobangalore.com",
    id: "APO001",
    password: "Apollo@123", // Original: Apollo@123
    phone: "9876543230",
    address: "789 Bangalore Road",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560001",
    specDrName: "C. Rao",
    numberOfDoctors: 60,
    numberOfNurses: 100,
    aboutHospital:
      "World-class medical facility in Bangalore offering advanced treatments and specialized care.",
    website: "https://apollobangalore.com",
    openingHours: { start: "08:00", end: "17:00" },
    experience: "20",
    specialist: "Neurologist",
    languagesSpoken: "English, Kannada, Tamil",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, DM Neurology",
    emergencyContact: "9876543231",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Santa Cruise Valley Hospital",
    email: "admin@santacruise.com",
    id: "SCV001",
    password: "Santa@123", // Original: Santa@123
    phone: "9876543240",
    address: "101 Mumbai Lane",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400002",
    specDrName: "D. Patil",
    numberOfDoctors: 35,
    numberOfNurses: 65,
    aboutHospital:
      "Specialized dermatology and general healthcare center in Mumbai.",
    website: "https://santacruise.com",
    openingHours: { start: "09:00", end: "18:00" },
    experience: "12",
    specialist: "Dermatologist",
    languagesSpoken: "English, Hindi, Marathi",
    insuranceAccepted: "Major insurance accepted",
    degree: "MBBS, MD Dermatology",
    emergencyContact: "9876543241",
    facilities: {
      Emergency: true,
      ICU: false,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: false,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: false,
      Maternity: false,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Care Hospital",
    email: "contact@carehospitalpune.com",
    id: "CARE001",
    password: "Care@123", // Original: Care@123
    phone: "9876543250",
    address: "121 Pune Street",
    city: "Pune",
    state: "Maharashtra",
    zipCode: "411001",
    specDrName: "E. Desai",
    numberOfDoctors: 40,
    numberOfNurses: 70,
    aboutHospital: "Trusted pediatric and family healthcare provider in Pune.",
    website: "https://carehospitalpune.com",
    openingHours: { start: "08:30", end: "18:00" },
    experience: "8",
    specialist: "Pediatrician",
    languagesSpoken: "English, Marathi, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, DCH",
    emergencyContact: "9876543251",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Metro Hospital",
    email: "info@metrohyd.com",
    id: "MET001",
    password: "Metro@123", // Original: Metro@123
    phone: "9876543260",
    address: "1234 Hyderabad Road",
    city: "Hyderabad",
    state: "Telangana",
    zipCode: "500001",
    specDrName: "F. Reddy",
    numberOfDoctors: 55,
    numberOfNurses: 95,
    aboutHospital: "Leading surgical and emergency care hospital in Hyderabad.",
    website: "https://metrohyd.com",
    openingHours: { start: "07:00", end: "17:00" },
    experience: "14",
    specialist: "General Surgeon",
    languagesSpoken: "English, Telugu, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MS General Surgery",
    emergencyContact: "9876543261",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Fortis Hospital",
    email: "contact@fortischennai.com",
    id: "FOR001",
    password: "Fortis@123", // Original: Fortis@123
    phone: "9876543270",
    address: "543 Chennai Blvd",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600001",
    specDrName: "G. Iyer",
    numberOfDoctors: 65,
    numberOfNurses: 110,
    aboutHospital:
      "Advanced orthopedic and multi-specialty hospital in Chennai.",
    website: "https://fortischennai.com",
    openingHours: { start: "10:00", end: "19:00" },
    experience: "18",
    specialist: "Orthopedic Surgeon",
    languagesSpoken: "English, Tamil, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MS Orthopedics",
    emergencyContact: "9876543271",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: false,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Max Health Care",
    email: "admin@maxhealthdelhi.com",
    id: "MAX001",
    password: "Max@123", // Original: Max@123
    phone: "9876543280",
    address: "678 Delhi Avenue",
    city: "Delhi",
    state: "Delhi",
    zipCode: "110002",
    specDrName: "H. Kapur",
    numberOfDoctors: 48,
    numberOfNurses: 85,
    aboutHospital:
      "Specialized ENT and multi-specialty healthcare center in Delhi.",
    website: "https://maxhealthdelhi.com",
    openingHours: { start: "09:00", end: "17:00" },
    experience: "11",
    specialist: "ENT Specialist",
    languagesSpoken: "English, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MS ENT",
    emergencyContact: "9876543281",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Lotus Hospital",
    email: "info@lotushospitaljaipur.com",
    id: "LOT001",
    password: "Lotus@123", // Original: Lotus@123
    phone: "9876543290",
    address: "333 Jaipur Lane",
    city: "Jaipur",
    state: "Rajasthan",
    zipCode: "302001",
    specDrName: "I. Singh",
    numberOfDoctors: 42,
    numberOfNurses: 75,
    aboutHospital: "Leading gynecology and maternity care hospital in Jaipur.",
    website: "https://lotushospitaljaipur.com",
    openingHours: { start: "08:00", end: "16:00" },
    experience: "16",
    specialist: "Gynecologist",
    languagesSpoken: "English, Hindi, Rajasthani",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MD Obstetrics & Gynecology",
    emergencyContact: "9876543291",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Medanta Hospital",
    email: "contact@medantagurgaon.com",
    id: "MED001",
    password: "Medanta@123", // Original: Medanta@123
    phone: "9876543300",
    address: "451 Gurgaon Circle",
    city: "Gurgaon",
    state: "Haryana",
    zipCode: "122001",
    specDrName: "J. Gupta",
    numberOfDoctors: 70,
    numberOfNurses: 120,
    aboutHospital: "Premier oncology and cancer treatment center in Gurgaon.",
    website: "https://medantagurgaon.com",
    openingHours: { start: "09:00", end: "18:30" },
    experience: "19",
    specialist: "Oncologist",
    languagesSpoken: "English, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MD Oncology",
    emergencyContact: "9876543301",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: false,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Rainbow Hospital",
    email: "admin@rainbowmumbai.com",
    id: "RAIN001",
    password: "Rainbow@123", // Original: Rainbow@123
    phone: "9876543310",
    address: "159 Rainbow Ave",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400003",
    specDrName: "K. Mehta",
    numberOfDoctors: 38,
    numberOfNurses: 68,
    aboutHospital:
      "Specialized pediatric care and child wellness center in Mumbai.",
    website: "https://rainbowmumbai.com",
    openingHours: { start: "08:30", end: "17:00" },
    experience: "7",
    specialist: "Pediatrician",
    languagesSpoken: "English, Hindi, Marathi",
    insuranceAccepted: "Major insurance accepted",
    degree: "MBBS, DCH",
    emergencyContact: "9876543311",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: false,
      Surgery: false,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: false,
      Maternity: true,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Ruby Hall Clinic",
    email: "contact@rubyhallpune.com",
    id: "RUBY001",
    password: "Ruby@123", // Original: Ruby@123
    phone: "9876543320",
    address: "256 Pune Street",
    city: "Pune",
    state: "Maharashtra",
    zipCode: "411002",
    specDrName: "L. Naik",
    numberOfDoctors: 44,
    numberOfNurses: 78,
    aboutHospital: "Advanced radiology and diagnostic center in Pune.",
    website: "https://rubyhallpune.com",
    openingHours: { start: "09:00", end: "19:00" },
    experience: "13",
    specialist: "Radiologist",
    languagesSpoken: "English, Marathi, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MD Radiology",
    emergencyContact: "9876543321",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Narayana Health",
    email: "info@narayanabangalore.com",
    id: "NAR001",
    password: "Narayana@123", // Original: Narayana@123
    phone: "9876543330",
    address: "101 Narayana Road",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560002",
    specDrName: "M. Kumar",
    numberOfDoctors: 68,
    numberOfNurses: 115,
    aboutHospital:
      "World-renowned cardiac care and heart hospital in Bangalore.",
    website: "https://narayanabangalore.com",
    openingHours: { start: "08:00", end: "16:00" },
    experience: "20",
    specialist: "Cardiologist",
    languagesSpoken: "English, Kannada, Tamil",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, DM Cardiology",
    emergencyContact: "9876543331",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: false,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "AIMS Hospital",
    email: "admin@aimskolkata.com",
    id: "AIMS001",
    password: "Aims@123", // Original: Aims@123
    phone: "9876543340",
    address: "321 Kolkata Road",
    city: "Kolkata",
    state: "West Bengal",
    zipCode: "700001",
    specDrName: "N. Banerjee",
    numberOfDoctors: 52,
    numberOfNurses: 92,
    aboutHospital: "Leading endocrinology and diabetes care center in Kolkata.",
    website: "https://aimskolkata.com",
    openingHours: { start: "10:00", end: "17:00" },
    experience: "22",
    specialist: "Endocrinologist",
    languagesSpoken: "English, Bengali, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MD Endocrinology",
    emergencyContact: "9876543341",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: false,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Sri Ramachandra Hospital",
    email: "contact@sriramachandra.com",
    id: "SRI001",
    password: "Sri@123", // Original: Sri@123
    phone: "9876543350",
    address: "789 Ramachandra Lane",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600002",
    specDrName: "O. Subramanian",
    numberOfDoctors: 58,
    numberOfNurses: 98,
    aboutHospital: "Specialized urology and kidney care hospital in Chennai.",
    website: "https://sriramachandra.com",
    openingHours: { start: "09:00", end: "17:00" },
    experience: "25",
    specialist: "Urologist",
    languagesSpoken: "English, Tamil",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MS Urology",
    emergencyContact: "9876543351",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: false,
      Pediatrics: false,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "St. John Medical Center",
    email: "info@stjohnbangalore.com",
    id: "STJ001",
    password: "StJohn@123", // Original: StJohn@123
    phone: "9876543360",
    address: "123 St. John Road",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560003",
    specDrName: "P. Iyer",
    numberOfDoctors: 46,
    numberOfNurses: 82,
    aboutHospital: "Premier eye care and ophthalmology hospital in Bangalore.",
    website: "https://stjohnbangalore.com",
    openingHours: { start: "08:00", end: "18:00" },
    experience: "15",
    specialist: "Ophthalmologist",
    languagesSpoken: "English, Kannada, Tamil",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MS Ophthalmology",
    emergencyContact: "9876543361",
    facilities: {
      Emergency: true,
      ICU: false,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: false,
      Maternity: false,
      Pediatrics: false,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Saket City Hospital",
    email: "admin@saketdelhi.com",
    id: "SAK001",
    password: "Saket@123", // Original: Saket@123
    phone: "9876543370",
    address: "100 Saket Avenue",
    city: "Delhi",
    state: "Delhi",
    zipCode: "110003",
    specDrName: "Q. Mehra",
    numberOfDoctors: 41,
    numberOfNurses: 72,
    aboutHospital:
      "Mental health and psychiatry specialized hospital in Delhi.",
    website: "https://saketdelhi.com",
    openingHours: { start: "10:00", end: "19:00" },
    experience: "12",
    specialist: "Psychiatrist",
    languagesSpoken: "English, Hindi",
    insuranceAccepted: "Major insurance accepted",
    degree: "MBBS, MD Psychiatry",
    emergencyContact: "9876543371",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: false,
      Surgery: false,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: false,
      Maternity: false,
      Pediatrics: false,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Cure Hospital",
    email: "contact@curehyd.com",
    id: "CURE001",
    password: "Cure@123", // Original: Cure@123
    phone: "9876543380",
    address: "87 Cure Lane",
    city: "Hyderabad",
    state: "Telangana",
    zipCode: "500002",
    specDrName: "R. Kumar",
    numberOfDoctors: 54,
    numberOfNurses: 94,
    aboutHospital: "Advanced nephrology and kidney care hospital in Hyderabad.",
    website: "https://curehyd.com",
    openingHours: { start: "09:00", end: "18:00" },
    experience: "18",
    specialist: "Nephrologist",
    languagesSpoken: "English, Telugu, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, DM Nephrology",
    emergencyContact: "9876543381",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: false,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Shanti Nursing Home",
    email: "info@shantichennai.com",
    id: "SHA001",
    password: "Shanti@123", // Original: Shanti@123
    phone: "9876543390",
    address: "234 Shanti Street",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600003",
    specDrName: "S. Reddy",
    numberOfDoctors: 36,
    numberOfNurses: 64,
    aboutHospital: "General medicine and family healthcare center in Chennai.",
    website: "https://shantichennai.com",
    openingHours: { start: "08:00", end: "18:00" },
    experience: "25",
    specialist: "General Physician",
    languagesSpoken: "English, Tamil",
    insuranceAccepted: "Major insurance accepted",
    degree: "MBBS, MD General Medicine",
    emergencyContact: "9876543391",
    facilities: {
      Emergency: true,
      ICU: false,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: false,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: false,
      Maternity: true,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Vasundhara Hospital",
    email: "admin@vasundharapune.com",
    id: "VAS001",
    password: "Vasundhara@123", // Original: Vasundhara@123
    phone: "9876543400",
    address: "456 Vasundhara Lane",
    city: "Pune",
    state: "Maharashtra",
    zipCode: "411003",
    specDrName: "T. Shah",
    numberOfDoctors: 39,
    numberOfNurses: 69,
    aboutHospital:
      "Gastroenterology and digestive care specialist hospital in Pune.",
    website: "https://vasundharapune.com",
    openingHours: { start: "09:00", end: "17:00" },
    experience: "10",
    specialist: "Gastroenterologist",
    languagesSpoken: "English, Marathi, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MD Gastroenterology",
    emergencyContact: "9876543401",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: false,
      Outpatient: true,
      BloodBank: true,
      Maternity: false,
      Pediatrics: true,
      Cardiology: false,
    },
    reviews: [],
  },
  {
    name: "Kokilaben Hospital",
    email: "contact@kokilabenmumbai.com",
    id: "KOK001",
    password: "Kokilaben@123", // Original: Kokilaben@123
    phone: "9876543410",
    address: "567 Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400053",
    specDrName: "U. Patel",
    numberOfDoctors: 72,
    numberOfNurses: 125,
    aboutHospital:
      "Multi-specialty tertiary care hospital with advanced medical technology in Mumbai.",
    website: "https://kokilabenmumbai.com",
    openingHours: { start: "08:00", end: "20:00" },
    experience: "17",
    specialist: "Neurosurgeon",
    languagesSpoken: "English, Hindi, Marathi, Gujarati",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MCh Neurosurgery",
    emergencyContact: "9876543411",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Yashoda Hospital",
    email: "info@yashodahyd.com",
    id: "YAS001",
    password: "Yashoda@123", // Original: Yashoda@123
    phone: "9876543420",
    address: "890 Secunderabad",
    city: "Hyderabad",
    state: "Telangana",
    zipCode: "500003",
    specDrName: "V. Rao",
    numberOfDoctors: 62,
    numberOfNurses: 105,
    aboutHospital:
      "Comprehensive healthcare with focus on critical care and emergency services in Hyderabad.",
    website: "https://yashodahyd.com",
    openingHours: { start: "00:00", end: "23:59" },
    experience: "21",
    specialist: "Critical Care Specialist",
    languagesSpoken: "English, Telugu, Hindi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MD Critical Care",
    emergencyContact: "9876543421",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "Manipal Hospital",
    email: "admin@manipalbangalore.com",
    id: "MAN001",
    password: "Manipal@123", // Original: Manipal@123
    phone: "9876543430",
    address: "98 HAL Airport Road",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560017",
    specDrName: "W. Shetty",
    numberOfDoctors: 75,
    numberOfNurses: 130,
    aboutHospital:
      "Leading multi-specialty hospital known for excellence in cancer care and transplants in Bangalore.",
    website: "https://manipalbangalore.com",
    openingHours: { start: "00:00", end: "23:59" },
    experience: "23",
    specialist: "Transplant Surgeon",
    languagesSpoken: "English, Kannada, Hindi, Tamil",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, MS, MCh Transplant Surgery",
    emergencyContact: "9876543431",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
  {
    name: "BLK Super Specialty Hospital",
    email: "contact@blkdelhi.com",
    id: "BLK001",
    password: "Blk@123", // Original: Blk@123
    phone: "9876543440",
    address: "456 Pusa Road",
    city: "Delhi",
    state: "Delhi",
    zipCode: "110005",
    specDrName: "X. Malhotra",
    numberOfDoctors: 80,
    numberOfNurses: 140,
    aboutHospital:
      "Super specialty hospital offering comprehensive healthcare with cutting-edge technology in Delhi.",
    website: "https://blkdelhi.com",
    openingHours: { start: "00:00", end: "23:59" },
    experience: "19",
    specialist: "Interventional Cardiologist",
    languagesSpoken: "English, Hindi, Punjabi",
    insuranceAccepted: "All major insurance",
    degree: "MBBS, DM Cardiology",
    emergencyContact: "9876543441",
    facilities: {
      Emergency: true,
      ICU: true,
      Pharmacy: true,
      Laboratory: true,
      Radiology: true,
      Surgery: true,
      Rehabilitation: true,
      Outpatient: true,
      BloodBank: true,
      Maternity: true,
      Pediatrics: true,
      Cardiology: true,
    },
    reviews: [],
  },
];

const patients = [
  {
    name: "Deepak Kusumkar",
    email: "deepakkusumkar2024.comp@mmcoe.edu.in",
    password: "D@123", // Original: D@123
    phone: "9123456781",
    dateOfBirth: new Date("1995-05-15"),
    address: "123 MG Road",
    city: "Mumbai",
    state: "Maharashtra",
    zipCode: "400001",
  },
  {
    name: "Abhishek Joshi",
    email: "abhishek.joshi@gmail.com",
    password: "A@123", // Original: A@123
    phone: "9123456782",
    dateOfBirth: new Date("1998-08-22"),
    address: "456 Park Street",
    city: "Delhi",
    state: "Delhi",
    zipCode: "110001",
  },
  {
    name: "Somesh Bharbade",
    email: "somesh.bharbade@gmail.com",
    password: "S@123", // Original: S@123
    phone: "9123456783",
    dateOfBirth: new Date("1997-03-10"),
    address: "789 Brigade Road",
    city: "Bangalore",
    state: "Karnataka",
    zipCode: "560001",
  },
  {
    name: "Rushikesh Karlekar",
    email: "rushikesh.karlekar@gmail.com",
    password: "R@123", // Original: R@123
    phone: "9123456784",
    dateOfBirth: new Date("1996-11-30"),
    address: "321 FC Road",
    city: "Pune",
    state: "Maharashtra",
    zipCode: "411001",
  },
  {
    name: "Vedant Patil",
    email: "vedant.patil@gmail.com",
    password: "V@123", // Original: V@123
    phone: "9123456785",
    dateOfBirth: new Date("1999-07-18"),
    address: "654 Banjara Hills",
    city: "Hyderabad",
    state: "Telangana",
    zipCode: "500001",
  },
  {
    name: "Yashwardhan Wayal",
    email: "yashwardhan.wayal@gmail.com",
    password: "Y@123", // Original: Y@123
    phone: "9123456786",
    dateOfBirth: new Date("1994-12-05"),
    address: "987 Anna Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    zipCode: "600001",
  },
  {
    name: "Rohit Pawar",
    email: "rohit.pawar@gmail.com",
    password: "R@123", // Original: R@123
    phone: "9123456787",
    dateOfBirth: new Date("2000-02-14"),
    address: "147 MI Road",
    city: "Jaipur",
    state: "Rajasthan",
    zipCode: "302001",
  },
  {
    name: "Rohan Shinde",
    email: "rohan.shinde@gmail.com",
    password: "R@123", // Original: R@123
    phone: "9123456788",
    dateOfBirth: new Date("1993-09-25"),
    address: "258 Sector 29",
    city: "Gurgaon",
    state: "Haryana",
    zipCode: "122001",
  },
  {
    name: "Amey Devshatwar",
    email: "amey.devshatwar@gmail.com",
    password: "A@123", // Original: A@123
    phone: "9123456789",
    dateOfBirth: new Date("1995-06-08"),
    address: "369 Park Street",
    city: "Kolkata",
    state: "West Bengal",
    zipCode: "700001",
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    await Hospital.deleteMany({});
    console.log("Cleared existing hospitals");

    await Client.deleteMany({});
    console.log("Cleared existing patients");

    const hashedHospitals = await Promise.all(
      hospitals.map(async (hospital) => {
        const hashedPassword = await bcrypt.hash(hospital.password, 10);
        return { ...hospital, password: hashedPassword };
      })
    );

    await Hospital.insertMany(hashedHospitals);
    console.log(`${hashedHospitals.length} hospitals inserted successfully`);

    const hashedPatients = await Promise.all(
      patients.map(async (patient) => {
        const hashedPassword = await bcrypt.hash(patient.password, 10);
        return { ...patient, password: hashedPassword };
      })
    );

    await Client.insertMany(hashedPatients);
    console.log(`${hashedPatients.length} patients inserted successfully`);

    console.log("\n✅ Seed completed successfully!");
    console.log("\nHospital Login Credentials (ID/Password):");
    hospitals.forEach((h) => {
      console.log(`${h.id} / ${h.password}`);
    });

    console.log("\nPatient Login Credentials (Email/Password):");
    patients.forEach((p) => {
      console.log(`${p.email} / ${p.password}`);
    });

    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
};

seedDatabase();
